services:
  pulseguard:
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    image: pulseguard:latest
    container_name: pulseguard
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"

